### ISSUE TITLE
attribute 'NOT'

### ISSUE THREAD

**Issue by KlausGrenoble** [MetaModels/bundle_attributes#1]
Proposal of a new feature: attribute 'NOT'. An example on the Darty-Website, there are products 'Exclusiv Internet'. If I want a list of all products in the store, I need a filter
'NOT' 'Exclusiv Internet'. Another example: All TVs without the feature '3D'.

**Comment by xantippe** [comment]
@KlausGrenoble Hallo Klaus, kannst Du nochmal genauer ausführen, was Du möchtest und ggf. Scrennshots bzw. direkte Links posten?

**Comment by KlausGrenoble** [comment]
Ich möchte nicht nur einen and-Filter sondern auch einen nand-Filter. Und für or ein nor.
http://www.darty.com/nav/achat/hifi_video/tous_ecrans_plats/index.html
In diesem Beispiel sieht man einen Filter für "ausschliesslich Internet". Heisst, dass ich diese Artikel im Darty-Kaufhaus nicht kaufen kann. Ich möchte aber gerade alle Artikel gelistet haben, die ich im Kaufhaus finde, also alles was nicht "ausschliesslich Internet" ist.
Auf der gleichen Seite gab es mal einen Filter "3D". Das sind die TV's mit der Brille. Die wollte ich auf alle Fälle nicht in meiner Liste, also einen Filter "not 3D". Alles klar ?

**Comment by xantippe** [comment]
siehe http://metamodels.readthedocs.org/de/latest/cookbook/filter/exclusion.html

Filterregel: "Suche alle Mitarbeiter die nicht in Abteilung xy sind"...

**Comment by andreasisaak** [comment]
Ich will ja nicht dazwischen grätschen aber ist das hier nicht das total falsche Ticket für sowas? Hier gehts um bundles, diese bundles haben in der Regel nicht mal eigene Tickets weil sie nur aus einer composer.json bestehen.

**Comment by xantippe** [comment]
ist hier fehl am Platze... k. wusste offensichtlich damals noch nicht wohin mit der Frage - aber ist ja eh geschlossen ;-)
