### ISSUE TITLE
Legenden werden nicht angezeigt

### ISSUE THREAD

**Issue by MarcelBurri** [MetaModels/bundle_attributes#2]
Habe für die BE-Eingabemaske eine Legende und darunter eine Checkbox erstellt.
Im Unterbereich der Checkbox habe ich ein paar Attribute eingefügt. Nun wollte ich denen noch einige Legenden verpassen, jedoch werden diejenigen aus dem Unterbereich in der Eingabemaske nicht angezeigt.

**Comment by zonky2** [comment]
Sub-Paletten und Legenden sind vorhanden
