### ISSUE TITLE
Leere Text-Tabelle ist nicht leer!

### ISSUE THREAD

**Issue by lucdesign** [MetaModels/bundle_attributes#3]
Habe erst nachher gesehen, dass es ein eigenes Repo für dieses Issue gibt ...

---

Wenn man eine Text-Tabelle einmal befüllt hat und später alle Elemente wieder löscht, bleibt eine "Geisterzeile" mit Leerstrings als Werten übrig. Im Template wird das als nicht-leeres Array erkannt.
Man kann diesen Fehler provisorisch mit der Abfrage
```php
<?php if ($this->raw[0][0]['value'] !== "") : ?>
```
abfangen. Das gleiche muss man aber auch prüfen, wenn man die Zeilen zählen will!

**Comment by discordier** [comment]
Du sprichst hierbei von `tl_metamodel_text` und somit von einem translated text attribut? Bitte issue dorthin.
Weiterhin bitte die Versionsnummern von MM Core und dem jeweiligen Attribut.

**Comment by lucdesign** [comment]
Ich nehme an, das gehört wohl eher zu attribute_translatedtabletext. Habs dort angelegt. Bin noch etwas neu hier, daher danke für den Tipp!

**Comment by discordier** [comment]
Merci.

Hier geht's weiter: MetaModels/attribute_translatedtabletext#10
